name: Bibliotek selvbetjeningspc
desktop:
  background_image_file: /assets/Sk-rmbillede-fra-2026-06-22-10-58-27.png
printer:
  printers:
    with_ppd:
      - printer-type: with_ppd
        name: bizhub-42
        display_name: Bizhub 42
        ip: 172.17.10.19
        protocol: ipp
        ppd_file: /assets/Bizhub-42.ppd
wifi:
  ssid: borgernet
  psk: bbbbb
  hidden: false
favorite_apps:
  apps:
    - org.gnome.Nautilus.desktop
    - org.mozilla.firefox.desktop
    - logout-button.desktop
firefox:
  urls:
    - https://biblioteket.sonderborg.dk/
mesh_agent:
  url: https://sikkerselvbetjening.org/demo/
  groupid: Sv6lSHK2gWTOr%40kd7qG1xGvtbTp%24qVsAcdzyWbUJmxcWBqz2M%404e1uDEUCGdJiug
