wake-sleep-schedule:
  monday:
    wake: 08:00
    sleep: 22:00
  tuesday:
    wake: 08:00
    sleep: 22:00
  wednesday:
    wake: 08:00
    sleep: 22:00
  thursday:
    wake: 08:00
    sleep: 22:00
  friday:
    wake: 08:00
    sleep: 22:00
  saturday:
    wake: 08:00
    sleep: 17:00
  sunday:
    wake: 08:00
    sleep: 17:00
