name: Børnebibliotek
description: Build image configuration for selvbetjeningsPCer på Biblioteket Sønderborg (børnebiblioteket)
policies:
  - ../policies/bibliotek-selvbetjeningspc.yml
  - ../policies/startside-boerneportalen.yml
image_id: selvbetjeningspc_sonderborg_boernebibliotek
