domains:
  - domain: demo
    groups:
      - name: nordborg
        desktop:
          background_image_file: config/assets/demo/jura.png
        printer:
          printers:
            - name: ricoh_c3010
              printer-type: with_ppd
              display_name: P11567 - Ricoh C3010
              protocol: socket
              ip: 10.1.1.30
              ppd_file: config/assets/demo/Ricoh-IM_C3010-PDF-Ricoh.ppd
              is_default: true
              settings:
                page_size: A4
                color_mode: rgb
                duplex: none
                orientation: portrait
        wifi:
          ssid: borgernet   # Required
          psk: ""           # Optional (can be left empty)
          hidden: false     # Optional (can be left empty)
        favorite-apps:
          apps:
            - org.gnome.Nautilus.desktop
            - org.mozilla.firefox.desktop
            - logout-button.desktop
    build_targets:
      - name: Nordborg
        description: Build image for Nordborg
        groups:
          - nordborg
        image_name: nordborg
