domains:
  - domain: demo
    policies:
      - id: sjkfhsuakxskajcs
        name: nordborg
        desktop:
          background_image_file: config/assets/demo/test.png
        printer:
          printers:
            - name: ricoh_c3015
              printer-type: with_ppd
              display_name: P11567 - Ricoh C3010
              protocol: socket
              ip: 10.1.1.30
              ppd_file: config/assets/demo/Ricoh-IM_C3010-PDF-Ricoh.ppd
              is_default: true
              settings:
                page_size: A4
                color_mode: rgb
                duplex: none
                orientation: portrait
        wifi:
          ssid: borgernet
          hidden: false
        favorite_apps:
          apps:
            - org.gnome.Nautilus.desktop
            - org.mozilla.firefox.desktop
            - logout-button.desktop
        firefox_urls:
          urls:
            - https://os2borgerpc.os2.eu/
        mesh_agent:
          url: https://sikkerselvbetjening.org/demo/
          groupid: Sv6lSHK2gWTOr%40kd7qG1xGvtbTp%24qVsAcdzyWbUJmxcWBqz2M%404e1uDEUCGdJiug
    device_groups:
      - id: 20&gotomesh=A7tZ1lm1HqXkM@QwI0R3DZm9rbJiGJRgSAym6DlksTftqy5A35wbjn@TsZJen55R
        name: Nordborg
        description: Build image for Nordborg
        policies:
          - sjkfhsuakxskajcs
        image_name: nordborg
